### ISSUE TITLE
No 'version' key in the manifest file for custom integration 

### ISSUE THREAD

**Issue by Verguldebarman** [jomwells/ambilights#22]
Current dev build of HA shows this warning:

`2021-03-04 15:28:46 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'philips_ambilight'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'philips_ambilight'`

More info can be found here: [https://www.home-assistant.io/blog/2021/03/03/release-20213/#breaking-changes](url) 
see **Custom integrations: Version warning**: 

> 
> Custom integrations now require a version key in their manifest file, this also means that all custom integrations now require a manifest file.
> 
> If you are using a legacy custom integration like custom_components/awesome.py this now needs to move to custom_components/awesome/__init__.py so you can add custom_components/awesome/manifest.json to it.
> 
> For more information about integration, manifests have a look here: https://developers.home-assistant.io/docs/creating_integration_manifest
> 
> For now, this will create a warning on startup. But this will eventually be blocked from loading if it’s missing a version in the manifest.

**Comment by DavidFFerreira** [comment]
this development is dead man...

**Comment by chillkiller** [comment]
@Verguldebarman https://github.com/jomwells/ambihue/issues/11#issuecomment-830707697

**Comment by chillkiller** [comment]
@Verguldebarman 

https://github.com/valexi7/ambilights
