### ISSUE TITLE
custom updater

### ISSUE THREAD

**Issue by h4nc** [jomwells/ambilights#3]
Would be nice to see this integrated in custom updater.

**Comment by nstrelow** [comment]
https://github.com/custom-components/custom_updater Link for reference

Actually not that hard, you only have to add a custom_components.json and put some links to the files on GitHub inside.

As an example: https://github.com/nstrelow/ha_philips_2016/blob/master/custom_components.json

**Comment by h4nc** [comment]
Nice, so do you add this to your next version? And also update the docs?

**Comment by nstrelow** [comment]
I am not the developer of this repo :P

Ask @jomwells

**Comment by h4nc** [comment]
In the meanwhile custom updater is depricated. 

Could you add support for HACS? 

https://community.home-assistant.io/t/custom-component-hacs/121727

**Comment by jomwells** [comment]
Again, my fault for constantly being behind on HA updates, looking into it now 👍

**Comment by jomwells** [comment]
I've split up the repos and (hopefully) added support for HACS for all three components, could you let me know if it is working for you using hacs custom repositories, and if it's all working I will see if I can get them added to the default list

**Comment by h4nc** [comment]
Just tested. It's works (installed ambihue and ambilights). However I did not try installing Ambilight+Yeelight as I don't have those lights.

**Comment by jomwells** [comment]
Perfect, thanks!

**Comment by h4nc** [comment]
Found one issue with ambihue

in switch.yaml

before:

`- platform: philips_ambihue`

now the example has to be changed to:

`- platform: philips_ambilight+hue `

**Comment by jomwells** [comment]
Good spot, fixed 👍
Thanks

**Comment by h4nc** [comment]
it stills shows up at the hacs page of ambi hue. Don't know when or how that page refreshes, but could cause confusion.

**Comment by jomwells** [comment]
Yeah it will for a while, I haven’t quite figured that out yet either, but restarting ha seemed to fix it for me, it just needs to pull the new info.md, all new users will see the updated text :)

**Comment by h4nc** [comment]
perfect
